# Generated by Django 6.0.6 on 2026-07-08 19:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SolicitudCompra",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "codigo",
                    models.CharField(editable=False, max_length=20, unique=True),
                ),
                ("fecha_registro", models.DateTimeField(auto_now_add=True)),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("Pendiente", "Pendiente"),
                            ("En Revision", "En Revision"),
                            ("Aprobada", "Aprobada"),
                            ("Rechazada", "Rechazada"),
                            ("Cotizada", "Cotizada"),
                            ("Orden Generada", "Orden Generada"),
                            ("Recibida", "Recibida"),
                            ("Completada", "Completada"),
                        ],
                        default="Pendiente",
                        max_length=20,
                    ),
                ),
                ("justificacion_rechazo", models.TextField(blank=True, null=True)),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ItemSolicitud",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("producto", models.CharField(max_length=100)),
                ("cantidad", models.PositiveIntegerField()),
                ("unidad_medida", models.CharField(max_length=20)),
                (
                    "solicitud",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="Compras_APP.solicitudcompra",
                    ),
                ),
            ],
        ),
    ]
