# Generated by Django 6.0.6 on 2026-07-08 19:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Compras_APP", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Proveedor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                ("ruc", models.CharField(max_length=20, unique=True)),
                ("direccion", models.CharField(max_length=200)),
                ("telefono", models.CharField(max_length=20)),
                ("email", models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name="SolicitudCotizacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                ("proveedores", models.ManyToManyField(to="Compras_APP.proveedor")),
                (
                    "solicitud_compra",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Compras_APP.solicitudcompra",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Cotizacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "precio_unitario",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("tiempo_entrega_dias", models.PositiveIntegerField()),
                ("vigencia_dias", models.PositiveIntegerField()),
                ("fecha_registro", models.DateTimeField(auto_now_add=True)),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("Pendiente", "Pendiente"),
                            ("Aceptada", "Aceptada"),
                            ("Rechazada", "Rechazada"),
                        ],
                        default="Pendiente",
                        max_length=20,
                    ),
                ),
                (
                    "proveedor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Compras_APP.proveedor",
                    ),
                ),
                (
                    "solicitud_cotizacion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cotizaciones",
                        to="Compras_APP.solicitudcotizacion",
                    ),
                ),
            ],
        ),
    ]
