# Generated by Django 6.0.6 on 2026-07-08 19:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Compras_APP", "0002_proveedor_solicitudcotizacion_cotizacion"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrdenCompra",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "codigo",
                    models.CharField(editable=False, max_length=20, unique=True),
                ),
                ("fecha_generacion", models.DateTimeField(auto_now_add=True)),
                (
                    "costo_total",
                    models.DecimalField(
                        decimal_places=2, editable=False, max_digits=12
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[("Pendiente", "Pendiente"), ("Recibida", "Recibida")],
                        default="Pendiente",
                        max_length=20,
                    ),
                ),
                (
                    "cotizacion",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Compras_APP.cotizacion",
                    ),
                ),
            ],
        ),
    ]
