# Generated by Django 6.0.6 on 2026-07-08 19:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Compras_APP", "0003_ordencompra"),
    ]

    operations = [
        migrations.CreateModel(
            name="RecepcionMercancia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha_recepcion", models.DateTimeField(auto_now_add=True)),
                ("observaciones", models.TextField(blank=True, null=True)),
                (
                    "orden_compra",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Compras_APP.ordencompra",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ItemRecepcion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cantidad_recibida", models.PositiveIntegerField()),
                (
                    "item_solicitud",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Compras_APP.itemsolicitud",
                    ),
                ),
                (
                    "recepcion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="Compras_APP.recepcionmercancia",
                    ),
                ),
            ],
        ),
    ]
