# Generated by Django 6.0.7 on 2026-07-08 16:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0002_alter_solicitudcompra_estado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('ruc', models.CharField(blank=True, max_length=20)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('correo', models.EmailField(blank=True, max_length=254)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='SolicitudCotizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('proveedores', models.ManyToManyField(related_name='solicitudes_cotizacion', to='compras.proveedor')),
                ('solicitud_compra', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='solicitud_cotizacion', to='compras.solicitudcompra')),
            ],
        ),
        migrations.CreateModel(
            name='Cotizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tiempo_entrega_dias', models.PositiveIntegerField()),
                ('vigencia', models.DateField()),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('ACEPTADA', 'Aceptada'), ('RECHAZADA', 'Rechazada')], default='PENDIENTE', max_length=20)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cotizaciones', to='compras.proveedor')),
                ('solicitud_cotizacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cotizaciones', to='compras.solicitudcotizacion')),
            ],
        ),
    ]
