# Generated by Django 6.0.7 on 2026-07-08 16:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0003_proveedor_solicitudcotizacion_cotizacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdenCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_orden', models.CharField(editable=False, max_length=20, unique=True)),
                ('costo_total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('fecha_generada', models.DateTimeField(auto_now_add=True)),
                ('cotizacion_ganadora', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='orden_compra', to='compras.cotizacion')),
            ],
        ),
    ]
