# Generated by Django 6.0.7 on 2026-07-08 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0004_ordencompra'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordencompra',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('RECIBIDA', 'Recibida')], default='PENDIENTE', max_length=20),
        ),
    ]
