# Generated by Django 6.0.7 on 2026-07-08 17:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0005_ordencompra_estado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recepcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_recibida', models.PositiveIntegerField()),
                ('observaciones', models.TextField(blank=True)),
                ('tiene_diferencia', models.BooleanField(default=False)),
                ('fecha_recepcion', models.DateTimeField(auto_now_add=True)),
                ('orden_compra', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='recepcion', to='compras.ordencompra')),
            ],
        ),
    ]
