# Generated by Django 6.0.7 on 2026-07-08 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0006_recepcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitudcompra',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('HAY_STOCK', 'Hay stock (atendida desde inventario)'), ('SIN_STOCK', 'Sin stock (pasa a cotización)'), ('APROBADA', 'Aprobada'), ('RECHAZADA', 'Rechazada'), ('COMPLETADA', 'Completada')], default='PENDIENTE', max_length=20),
        ),
    ]
